export interface BibleBookDefinition {
  canonical: string;
  aliases: string[];
}

export const bibleBooks: BibleBookDefinition[] = [
  { canonical: "Genesis", aliases: ["genesis"] },
  { canonical: "Exodo", aliases: ["exodo"] },
  { canonical: "Levitico", aliases: ["levitico"] },
  { canonical: "Numeros", aliases: ["numeros"] },
  { canonical: "Deuteronomio", aliases: ["deuteronomio"] },
  { canonical: "Josue", aliases: ["josue"] },
  { canonical: "Juizes", aliases: ["juizes"] },
  { canonical: "Rute", aliases: ["rute"] },
  { canonical: "1 Samuel", aliases: ["primeiro samuel", "1 samuel"] },
  { canonical: "2 Samuel", aliases: ["segundo samuel", "2 samuel"] },
  { canonical: "1 Reis", aliases: ["primeiro reis", "1 reis"] },
  { canonical: "2 Reis", aliases: ["segundo reis", "2 reis"] },
  { canonical: "1 Cronicas", aliases: ["primeiro cronicas", "1 cronicas"] },
  { canonical: "2 Cronicas", aliases: ["segundo cronicas", "2 cronicas"] },
  { canonical: "Esdras", aliases: ["esdras"] },
  { canonical: "Neemias", aliases: ["neemias"] },
  { canonical: "Ester", aliases: ["ester"] },
  { canonical: "Jo", aliases: ["jo"] },
  { canonical: "Salmos", aliases: ["salmos", "salmo"] },
  { canonical: "Proverbios", aliases: ["proverbios"] },
  { canonical: "Eclesiastes", aliases: ["eclesiastes"] },
  { canonical: "Cantares", aliases: ["cantares", "canticos"] },
  { canonical: "Isaias", aliases: ["isaias"] },
  { canonical: "Jeremias", aliases: ["jeremias"] },
  { canonical: "Lamentacoes", aliases: ["lamentacoes"] },
  { canonical: "Ezequiel", aliases: ["ezequiel"] },
  { canonical: "Daniel", aliases: ["daniel"] },
  { canonical: "Oseias", aliases: ["oseias"] },
  { canonical: "Joel", aliases: ["joel"] },
  { canonical: "Amos", aliases: ["amos"] },
  { canonical: "Obadias", aliases: ["obadias"] },
  { canonical: "Jonas", aliases: ["jonas"] },
  { canonical: "Miqueias", aliases: ["miqueias"] },
  { canonical: "Naum", aliases: ["naum"] },
  { canonical: "Habacuque", aliases: ["habacuque"] },
  { canonical: "Sofonias", aliases: ["sofonias"] },
  { canonical: "Ageu", aliases: ["ageu"] },
  { canonical: "Zacarias", aliases: ["zacarias"] },
  { canonical: "Malaquias", aliases: ["malaquias"] },
  { canonical: "Mateus", aliases: ["mateus", "matheus"] },
  { canonical: "Marcos", aliases: ["marcos"] },
  { canonical: "Lucas", aliases: ["lucas"] },
  { canonical: "Joao", aliases: ["joao", "evangelho de joao"] },
  { canonical: "Atos", aliases: ["atos"] },
  { canonical: "Romanos", aliases: ["romanos"] },
  { canonical: "1 Corintios", aliases: ["primeira corintios", "primeiro corintios", "1 corintios"] },
  { canonical: "2 Corintios", aliases: ["segunda corintios", "segundo corintios", "2 corintios"] },
  { canonical: "Galatas", aliases: ["galatas"] },
  { canonical: "Efesios", aliases: ["efesios"] },
  { canonical: "Filipenses", aliases: ["filipenses"] },
  { canonical: "Colossenses", aliases: ["colossenses"] },
  { canonical: "1 Tessalonicenses", aliases: ["primeira tessalonicenses", "1 tessalonicenses"] },
  { canonical: "2 Tessalonicenses", aliases: ["segunda tessalonicenses", "2 tessalonicenses"] },
  { canonical: "1 Timoteo", aliases: ["primeira timoteo", "primeiro timoteo", "1 timoteo"] },
  { canonical: "2 Timoteo", aliases: ["segunda timoteo", "segundo timoteo", "2 timoteo"] },
  { canonical: "Tito", aliases: ["tito"] },
  { canonical: "Filemom", aliases: ["filemom"] },
  { canonical: "Hebreus", aliases: ["hebreus"] },
  { canonical: "Tiago", aliases: ["tiago"] },
  { canonical: "1 Pedro", aliases: ["primeira pedro", "primeiro pedro", "1 pedro"] },
  { canonical: "2 Pedro", aliases: ["segunda pedro", "segundo pedro", "2 pedro"] },
  { canonical: "1 Joao", aliases: ["primeira joao", "primeiro joao", "1 joao"] },
  { canonical: "2 Joao", aliases: ["segunda joao", "segundo joao", "2 joao"] },
  { canonical: "3 Joao", aliases: ["terceira joao", "terceiro joao", "3 joao"] },
  { canonical: "Judas", aliases: ["judas"] },
  { canonical: "Apocalipse", aliases: ["apocalipse"] }
];
